### ISSUE TITLE
Pip install not working

### ISSUE THREAD

**Issue by afcarvalho1991** [D2KLab/entity2rec#2]
Hello,

I'm using a mac to try running the project. 
After executing:
         pip install gensim networkx pandas SPARQLWrapper 

I was getting a error saying six was depreacted. I added  "--ignore-installed" to the command resulting in
        pip install gensim networkx pandas SPARQLWrapper --ignore-installed

As result :
[out.txt](https://github.com/MultimediaSemantics/entity2rec/files/1407549/out.txt)

If I use sudo pip ...
[out_sudo.txt](https://github.com/MultimediaSemantics/entity2rec/files/1407548/out_sudo.txt)

> creating /System/Library/Frameworks/Python.framework/Versions/2.7/share
>     error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted
>     
>     ----------------------------------------
> Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-svC5Wg/networkx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-4WAyVF-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-svC5Wg/networkx/

If I execute "src/entity2rec.py" the output is the following:

> /Library/Python/2.7/site-packages/networkx/drawing/nx_pydot.py:27: UserWarning: Module networkx was already imported from /Library/Python/2.7/site-packages/networkx/__init__.pyc, but /Library/Python/2.7/site-packages/networkx-2.0-py2.7.egg is being added to sys.path
>   from pkg_resources import parse_version
> Traceback (most recent call last):
>   File "entity2rec.py", line 368, in <module>
>     rec = Entity2Rec(args.directed, args.preprocessing, args.weighted, args.p, args.q, args.walk_length, args.num_walks, args.dimensions, args.window_size, args.workers, args.iter, args.config_file, args.sparql, args.dataset, args.entities, args.default_graph, args.train, args.test, args.implicit, args.entity_class, args.feedback_file)
>   File "entity2rec.py", line 22, in __init__
>     Entity2Vec.__init__(self, is_directed, preprocessing, is_weighted, p, q, walk_length, num_walks, dimensions, window_size, workers, iterations, config, sparql, dataset, entities, default_graph, entity_class, feedback_file)
>   File "/Users/andrecarvalho/Desktop/entity2rec/src/entity2vec.py", line 40, in __init__
>     self._define_properties()
>   File "/Users/andrecarvalho/Desktop/entity2rec/src/entity2vec.py", line 44, in _define_properties
>     with codecs.open(self.config_file, 'r', encoding='utf-8') as config_read:
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 884, in open
>     file = __builtin__.open(filename, mode, buffering)
> IOError: [Errno 2] No such file or directory: 'config/properties.json'

Any advice? 

Thanks, 
André Carvalho

**Comment by enricopal** [comment]
Hi André,
about pip, I see that you get a "permission denied" error, you probably have to do "sudo pip...".
About the 'IOError' that you get, from where are you launching the python command? As you can see in the commands reported in the https://github.com/MultimediaSemantics/entity2rec/wiki, you should launch the command from the entity2rec folder and not from the src/ folder, otherwise, it will look for a config/ folder inside src/, which does not exist.

**Comment by afcarvalho1991** [comment]
Didn't saw the wiki tab! 
I let you know if it worked!

Thanks for the quick reply,
André

PS: Should be included a link for the how-to experiment (the wiki page) at the README.md ! :)

**Comment by enricopal** [comment]
About pip, it seems that it is a OSX problem, they suggest to use pip --user https://github.com/gevent/gevent/issues/679
There is already a link to the Wiki in the README.md.
Let me know how it goes,
Enrico

**Comment by afcarvalho1991** [comment]
In OSX, the cut command accounts for order, as result the command:
  - cut -f1,2 datasets/movielens_1m/train.dat -d' ' > datasets/movielens_1m/graphs/feedback.edgelist

needs to be: 
 - cut -f1,2 -d ' '  datasets/movielens_1m/train.dat  > datasets/movielens_1m/graphs/feedback.edgelist

Still not working, I reinstalled the networkx-2.0 using the source code, and then ran as instructed in the wiki page
The output was: [out.txt](https://github.com/MultimediaSemantics/entity2rec/files/1407711/out.txt)

**Comment by afcarvalho1991** [comment]
Solved.
