### ISSUE TITLE
Wiki instructions for RankLib

### ISSUE THREAD

**Issue by rbramley** [D2KLab/entity2rec#3]
The command for RankLib is incorrect as the test/training filenames contain `_p1_q1`. 

The accompanying patch (_.txt extension added to enable it to be attached_) fixes that and adds a note about Java memory usage (**spoiler alert**: `-Xmx10G`).

[patch.diff.txt](https://github.com/D2KLab/entity2rec/files/1971867/patch.diff.txt)

**Comment by enricopal** [comment]
Thanks for spotting this @rbramley, I've modified the description accordingly.
