### ISSUE TITLE
how to map MovieLens 1M data to the DBpedia?

### ISSUE THREAD

**Issue by wangwangbobo** [D2KLab/entity2rec#4]
Hello, I want to map movielens datasets to a knowledge graph,but want I find knowledge graph datasets is uri2id,rather than the really entity or relation to id,so  I want to know how can I map  the two datasets?

**Comment by enricopal** [comment]
Hi, I think that this is what you are looking for: https://github.com/sisinflab/LODrecsys-datasets/tree/master/Movielens1M

**Comment by rtroncy** [comment]
Can you confirm @wangwangbobo so we can close this issue?

**Comment by wangwangbobo** [comment]
yes,thank you very much!
